[package]
name = "h3"
version = "0.0.0"
authors = [
    "Sean McArthur <sean@seanmonstar.com>",
    "Jean-Christophe BEGUE <jc.begue@pm.me>",
]
license = "MIT"
edition = "2018"

[dependencies]
bytes = "1"
futures-util = { version = "0.3", default-features = false }
http = "0.2.3"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1.18"
fastrand = "1.7.0"

[dev-dependencies]
pin-project = "1.0.12"
assert_matches = "1.3.0"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
proptest = "1"
quinn = { version = "0.9.0", default-features = false, features = [
    "ring",
    "runtime-tokio",
    "tls-rustls",
] }
quinn-proto = { version = "0.9", default-features = false }
rcgen = "0.9"
rustls = "0.20"
tokio = { version = "1", features = ["rt", "macros", "io-util", "io-std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "ansi",
    "env-filter",
    "time",
    "tracing-log",
] }
